[Admin]
def_DataNetworkPath = 
;=""
;==========================================================================================""
;----------------------------------------USER Dialog --------------------------------------""
;==========================================================================================""
;=""

[UserDialog]
Operator = "1010"
Device_SN = "001"
Lens options = "2"
Wavelength laser = 8.950000E+2
Subcarrier type = "3"
Max. current LD = 1.500000E+2
Operating current LD w/o folding = 1.300000E+2
Operating current LD w/ folding = 1.000000E+2
Operating current VBG = 1.000000E+2
Grid current VBG = 4.000000E+1
Facet current VBG = 6.000000E+1
Part number = "16"
Axis name = "Align_Yaw2"
;==========================================================================================""
;------------------------------------------Matrix ----------------------------------------=""
;==========================================================================================""

[InitMatrixSwitch]
MatrixSwitchComandDelay = 100G
;--------- Settings for  --------
MatrixInput_Init = 3,4,5,6,7,8
MatrixOutput_Init = 10,9,13,2,14,1
;==========================================================================================""
;------------------------------------------Vision ----------------------------------------=""
;==========================================================================================""

[Vision_Pickup_BallLens]
Illu_Coax = 1.0
Zoom_ExpTime = 9.98E+3
Illu_1 = 0.6
Illu_2 = 0

[Vision_dipping]
Illu_Coax = 1.0
Zoom_ExpTime = 9.98E+3
Illu_1 = 0.4
Illu_2 = 0

[Vision_Fixing]
Illu_Coax = 0.8
Zoom_ExpTime = 7.3E+3
Illu_1 = 1.0
Illu_2 = 1.0

[Vision_Chip_MirrorFront]
Illu_Coax = 0.15
Zoom_ExpTime = 2.35E+5
Illu_1 = 0.5
Illu_2 = 1.0

[Vision_Chip_MirrorSide]
Illu_Coax = 0.3
Zoom_ExpTime = 2.35E+5
Illu_1 = 0.5
Illu_2 = 0.05

[Vision_Chip_Top]
Illu_Coax = 0.08
Zoom_ExpTime = 7.35E+4
Illu_1 = 0.0
Illu_2 = 0.0

[Vision_Camera_High]
Illu_Coax = 0.8
Zoom_ExpTime = 5E+5
Illu_1 = 0.00
Illu_2 = 0.00

[Vision_Camera_Medium]
Illu_Coax = 0.8
Zoom_ExpTime = 5E+4
Illu_1 = 0.00
Illu_2 = 0.00

[Vision_Camera_Low]
Illu_Coax = 0.8
Zoom_ExpTime = 8E+3
Illu_1 = 0.00
Illu_2 = 0.00
;JL Fine spiral Scan
;3, 1, 20, cont, 10, 10
;==========================================================================================""
;------------------------------------------Scaling ---------------------------------------=""
;==========================================================================================""

[Scaling]
HFA_Top_1 = 4.15
HFA_Chip_YawAlignment = 2.2678
;==========================================================================================""
;----------------------------------------Curing time -------------------------------------=""
;==========================================================================================""

[Cure_Time]
HFA = 80000
;==========================================================================================""
;---------------------------Process LA - Lens Alignment -------------------------=""
;==========================================================================================""

[PosPickUp_BallLens]
;---------------Align_1-------------
Align_X1 = -1.410034E+4
Align_Y1 = -1.380009E+3
Align_Z1 = 3.459987E+4
Align_Roll1 = 0.000000E+0
Align_Pitch1 = 0.000000E+0
Align_Yaw1 = 0.000000E+0
;---------------Align_2-------------
Align_X2 = 37999.997
Align_Y2 = 40000.003
Align_Z2 = -80000.052
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 0
;---------------Camera-------------
Camera_X = -7.500525E+4
Camera_Y = -4.499850E+4
Camera_Z = -6.100425E+4
Camera_Zoom = 0.000000E+0

[Pos_Dripping]
;---------------Align_1-------------
Align_X1 = 5899.982
Align_Y1 = -2849.995
Align_Z1 = 36699.998
Align_Roll1 = 0
Align_Pitch1 = 0
Align_Yaw1 = 0
;---------------Align_2-------------
Align_X2 = 37999.997
Align_Y2 = 40000.003
Align_Z2 = -80000.052
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 0
;---------------Camera-------------
Camera_X = -51807.750
Camera_Y = -44998.500
Camera_Z = -59004.750
Camera_Zoom = 0.0

[Pos_Fixing]
;---------------Align_1-------------
Align_X1 = 1.690010E+4
Align_Y1 = -3.995024E+3
Align_Z1 = 7.000695E+2
Align_Roll1 = 0.000000E+0
Align_Pitch1 = 0.000000E+0
Align_Yaw1 = 0.000000E+0
;---------------Align_2-------------
Align_X2 = 37999.997
Align_Y2 = 40000.003
Align_Z2 = -80000.052
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 0
;---------------Camera-------------
Camera_X = -3.870525E+4
Camera_Y = -4.499775E+4
Camera_Z = -9.540375E+4
Camera_Zoom = 2.100000E+3
Camera_Y_Gripper = -51702.0

[Pos_Pick_LA_Wide_Leave]
;---------------Align_1-------------
Align_Y1_Offset = 0
;---------------Align_2-------------
Align_Y2_Offset = 15000
;---------------Camera-------------
Camera_Y_Offset = 30000
;---------------------------------------------- CHIP ----------------------------------------------

[Pos_Chip_LA_Wide_Init]
;---------------Align_1-------------
Align_X1 = -25000.0
Align_Y1 = 30000.0
Align_Z1 = 81000.0
Align_Roll1 = 0
Align_Pitch1 = 0
Align_Yaw1 = 0
;---------------Align_2-------------
Align_X2 = -24750.0
Align_Y2 = 10570.0
Align_Z2 = -5100.0
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 0
;---------------Camera-------------
Camera_X = -53399.0
Camera_Y = -38500.0
Camera_Z = -122271.0
Camera_Zoom = 0.0

[Pos_Chip_LA_Wide_Mirror_Front]
;---------------Align_1-------------
Align_X1 = -25000.0
Align_Y1 = 30000.0
Align_Z1 = 81000.0
;---------------Align_2-------------
Align_X2 = -23749.978
Align_Y2 = -1940.0
Align_Z2 = 9900.016
;---------------Camera-------------
Camera_X = -48101.000
Camera_Y = -64000.000
Camera_Z = -105101.000
Camera_Zoom = 1000.0

[Pos_Chip_LA_Wide_Mirror_Side]
;---------------Align_1-------------
Align_X1 = -25000.0
Align_Y1 = 30000.0
Align_Z1 = 81000.0
;---------------Align_2-------------
Align_X2 = -23749.964
Align_Y2 = -1940.007
Align_Z2 = 100.0
;---------------Camera-------------
Camera_X = -33399.000
Camera_Y = -66503.000
Camera_Z = -130274.000
Camera_Zoom = 1500.000

[Pos_Chip_LA_Wide_Top]
;---------------Align_1-------------
Align_X1 = -25000.0
Align_Y1 = 30000.0
Align_Z1 = 81000.0
Align_Roll1 = 0
Align_Pitch1 = 0
Align_Yaw1 = 0
;---------------Align_2-------------
Align_X2 = -22014.406
;Y2 - 100um lower to be 20um over the chip
Align_Y2 = -2520.0
Align_Z2 = -6379.987
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 500
;---------------Camera-------------
Camera_X = -45951.000
Camera_Y = -57721.000
Camera_Z = -137551.000
Camera_Zoom = 2000

[Pos_Chip_LA_Wide_Leave]
;---------------Align_1-------------
Align_Y1_Offset = 0
;---------------Align_2-------------
Align_Y2_Offset = 15000
;---------------Camera-------------
Camera_Y_Offset = 30000

[Pos_LA_Wide_Alignment]
;---------------Align_1-------------
Align_X1 = 0.000000E+0
Align_Y1 = 0.000000E+0
Align_Z1 = 0.000000E+0
Align_Roll1 = 0.000000E+0
Align_Pitch1 = 0.000000E+0
Align_Yaw1 = 0.000000E+0
;---------------Align_2-------------
Align_X2 = 0.000000E+0
Align_Y2 = 0.000000E+0
Align_Z2 = 0.000000E+0
Align_Roll2 = 0.000000E+0
Align_Pitch2 = 0.000000E+0
Align_Yaw2 = 0.000000E+0

[Offsets_LA_Wide_Alignment]
Align_X2_Offset = 75.0
Align_Z2_Offset = 133.0

[Pos_Dispense_LA_Wide]
;---------------Align_1-------------
Align_X1 = -3.900000E+4
Align_Y1 = -3.500000E+4
Align_Z1 = 5.304045E-3
Align_Roll1 = 0.000000E+0
Align_Pitch1 = 3.780378E+0
Align_Yaw1 = 0.000000E+0
;---------------Align_2-------------
Align_X2 = 39000
Align_Y2 = -35000.000
Align_Z2 = 0
Align_Roll2 = 0
Align_Pitch2 = 0
Align_Yaw2 = 0
;---------------Camera-------------
Camera_X = -48500.000
Camera_Y = -56965.000
Camera_Y_OverTheChip = -56852.000
Camera_Z = -136950.000

[Pos_Cure_UV_Left_LA_Wide]
;---------------Camera-------------
Camera_X = -25201.0
Camera_Y = -56865.0
Camera_Z = -79700.0

[Pos_Cure_UV_Right_LA_Wide]
;---------------Camera-------------
Camera_X = -59700.0
Camera_Y = -56865.0
Camera_Z = -79200.0

[TravelOffset_AfterCuring_LA_Wide]
Align_Y2_Offset = 15000
Align_Z2_Offset = -30000

[TravelOffset_AfterAlignment_LA_Wide]
Align_Y2_Offset = 500
Align_Z2_Offset = -2000

[ProcessDataLA_Wide]
;---------------Align_1-------------
Align_X1 = 0.000000E+0
Align_Y1 = 0.000000E+0
Align_Z1 = 0.000000E+0
Align_Roll1 = 0.000000E+0
Align_Pitch1 = 0.000000E+0
Align_Yaw1 = 0.000000E+0
;---------------Align_2-------------
Align_X2 = -2.228339E+4
Align_Y2 = -2.662992E+3
Align_Z2 = -6.662374E+3
Align_Roll2 = 2.510000E+2
Align_Pitch2 = -1.620193E+2
Align_Yaw2 = 2.510000E+2
Power_Aligned = 1.247582E-1
;==========================================================================================""
;-------------------------- rest -------------------------=""
;==========================================================================================""

[Master_FA]
AbortProcess = "0.000000E+0"
StartTimeProcess = 6.074116E+6
EndTimeProcess = 1.196472E+3
ProcessDuration = 2.283208E+1
ProcessDateTime = "12/10/2023 10:52:17"
CurrentProcess = "FA_Alignment"
EngMode = 0
TestMode = 0
MiniReportFieldNumber = 0.000000E+0
CurrentStep = "Lo"
PartNumber = 2.000000E+1

[MainInitEquipment]
TIA1Offset = 0
TIA1Range = 5
TIA1Wavelength = 1550
TIA1Polarity = Non-Inverting
TIA2Offset = 0
TIA2Range = 5
TIA2Wavelength = 1500
TIA2Polarity = Inverting
;TIA2Polarity = Non-Inverting
CalibrationFactor = 1000
;Calibration factor=0.001 (Factor mW/A) * 
;=""
;==========================================================================================""
;----------------------------------------References --------------------------------------=""
;==========================================================================================""
;=""
;=""
;==========================================================================================""
;----------------------------------------Beamprofiling Setups--------------------------------------=""
;==========================================================================================""
;=""

[PreDispensing]
CameraX = 22512.295
CameraY = 134930
CameraZ = -48550.433

[MainDispensing]
Offset_Y = 1000
Offset_Z = -800
DispenseCycleLo = 2
DispenseCycleLo2 = 0
;
DispenseCycleTxRx = 2
DispenseCycleTxRx2 = 1
Dispensing_Lo = 800
Dispensing_TxRx = 1000

[MainUVCuring]
Align_X2_UVOffset = 0
Align_Y2_UVOffset = 0
Camera_X_Rel = -2.554600E+4
Camera_Y_Rel = 1.414520E+5
Camera_Z_Rel = -1.794100E+4
Camera_X_Lo = -2.369597E+4
Camera_X_TxRx = -2.554597E+4
Camera_Y_Lo = 1.414520E+5
Camera_Z_Lo = -1.794097E+4
;Camera_X_Lo = 8843
;Camera_X_TxRx = 7143
;Camera_Y_Lo = 145373
;Camera_Z_Lo = -40710
TravelHightUV = 0
Camera_X_Rel_TxRx = -2.554600E+4
Camera_Y_Rel_TxRx = 1.414520E+5
Camera_Z_Rel_TxRx = -1.794100E+4
Camera_X_Rel_Lo = -2.369600E+4
Camera_Y_Rel_Lo = 1.414520E+5
Camera_Z_Rel_Lo = -1.794100E+4

[UV_Calibration]
Camera_X_Rel = -300
Camera_Y_Rel = -1330
Camera_Z_Rel = -10600
Camera_X = -25246
Camera_Y = 142782
Camera_Z = -7341

[UVProfile_Lo]
Repeat1 = 20
DurationOn1 = 1
DurationOff1 = 1
UV_IntensityOn1 = 35
;
Repeat2 = 15
DurationOn2 = 2
DurationOff2 = 2
UV_IntensityOn2 = 45
;
Repeat3 = 10
DurationOn3 = 2
DurationOff3 = 2
UV_IntensityOn3 = 55
;
UV_CompY2 = 1.0

[UVProfile_TxRx]
Repeat1 = 20
DurationOn1 = 1
DurationOff1 = 1
UV_IntensityOn1 = 35
;
Repeat2 = 15
DurationOn2 = 2
DurationOff2 = 2
UV_IntensityOn2 = 45
;
Repeat3 = 15
DurationOn3 = 2
DurationOff3 = 2
UV_IntensityOn3 = 55
;
UV_CompY2 = 1.2

[UVProfile_AfterRelease]
Repeat1 = 20
DurationOn1 = 1
DurationOff1 = 1
UV_IntensityOn1 = 60
;Repeat1 = 1
;DurationOn1 = 60
;DurationOff1 = 0
;UV_IntensityOn1 = 85

[ROI]
ROI_X_UP = 5.230000E+2
ROI_X_Down = 1.523000E+3
ROI_Y_UP = 5.900000E+2
ROI_Y_Down = 1.590000E+3
GripperCenter_X = "1.534000E+3"
GripperCenter_Y = "1.577000E+3"
TxRx_FACenter_X = 1170
TxRx_FACenter_Y = 1030
Lo_FACenter_X = 1200
Lo_FACenter_Y = 1030
;
TxRxX = 1.272000E+3
TxRxY = 7.690000E+2
LoX = 1.290000E+3
LoY = 9.760000E+2
GripperX = 1.255000E+3
GripperY = 1.048000E+3
;
TxRx_Chip_X = 1.467000E+3
TxRx_Chip_Y = 8.260000E+2
TxRx_Place_Y = 1.530000E+3
TxRx_Place_X = 1.361000E+3
;
Lo_Chip_X = 1.255000E+3
Lo_Chip_Y = 9.290000E+2
Lo_Place_Y = 1.454000E+3
Lo_Place_X = 1.385000E+3
ChipEdgeX1 = 300
ChipEdgeY1 = 700
ChipEdgeX2 = 2200
ChipEdgeY2 = 1100
FAEdgeX1 = 6.670000E+2
FAEdgeY1 = 1.900000E+2
FAEdgeX2 = 2100
FAEdgeY2 = 1.819000E+3

[Error]
Error = 1.000000E+0
ErrorDescription = "SysGraNSaveImage; 02/02/2023 16:12:10 "
ErrorSequence = "SUB_MatrixSwitchSingleChannel"
ErrorDate = "06/08/2023 13:48:19"
ErrorMessage = "Matrix switch error! The response of the matrix switch is not equal with the comand!\0D\0AAll sequences will be aborted! Call the setup!"

[TimeLogging]
Time_SUB_MainMoveToStartPos = "1.5"
Time_SUB_MainMoveTrayIn = "0.8"
Time_SUB_MoveCamera = "5.9"
Time_SUB_MainDeviceHandling = "15.5"
Time_SUB_SysDMS_Gripper2 = "2.7"
Time_SUB_MainPickupFALo = "71.1"
Time_SUB_YawAngleCorrection = "15.4"
Time_SUB_MainMoveFAtoChipLo = "86.9"
Time_SUB_MainLoAlignment = "44.7"
Time_SUB_MainDispensing_Lo = "64.9"
Time_SUB_MoveCameraToUV = "7.6"
Time_SUB_MainLoReAlignmentAfterDispense = "13.0"
Time_SUB_MainUVCuringLo = "227.0"
Time_SUB_ReleaseGripperAfterUV = "3.5"
Time_SUB_MainUVCuringAfterReleaseLo = "50.9"
Time_SUB_MainPickupFATxRx = "54.3"
Time_SUB_MainMoveFAtoChipTxRx = "64.0"
Time_SUB_MainTxRxAlignment = "148.9"
Time_SUB_MainDispensing_TxRx = "55.0"
Time_SUB_MainTxRxReAlignmentAfterDispense = "26.3"
Time_SUB_MainUVCuringTxRx = "255.9"
Time_SUB_MainUVCuringAfterReleaseTxRx = "48.7"
Time_SUB_ReadFinalPower = "10.0"
Time_Master_FA = "384.3"
Time_MainSaveProcessData = "1.1"
Time_SUB_MainPowerRead = "30.6"
Time_SaveData_PowerRead = "0.1"
Time_SUB_ReDispensing_Lo = "49.9"
Time_SUB_ReDispensing_TxRx = "41.0"
Time_SUB_MainReturnFA = "61.9"
Time_Master_FA_TxRx = "59578.1"
Time_Master_FA_LO = "406742.2"
Time_ = "81247.6"
Time_SUB_MainDistanceMeasurement = "3.8"
SysGraNSaveImage = 3.100000E-2
Time_SUB_MainInitEquipment = "0.5"
Time_SUB_MainPickupFAHFA = "42.8"
Time_SUB_Pick_Top_Correction = "9.0"
Time_SUB_Chip_MirrorFront_Correction = "5.4"
Time_SUB_Chip_MirrorSide_Correction = "5.1"
Time_SUB_MainChipFAHFA = "70.7"
Time_SUB_Chip_Top_Correction = "11.4"
Time_SUB_MainAlignmentHFA = "165.4"
Time_SUB_MoveFiberByOffset_FA = "1.8"

[FA_Lo_ReturnPos]
FA_Lo_X = 3.042841E+2
FA_Lo_Y = -6.365275E+3
FA_Lo_Z = -8.497136E+3

[FA_TxRx_ReturnPos]
FA_TxRx_X = -1.426748E+3
FA_TxRx_Y = -6.256046E+3
FA_TxRx_Z = -8.462436E+3

[ProcessDataData]
Align_Pitch2_Diff = 0.000000E+0

[SavePositionData]
Align_Yaw2_Diff = 0.000000E+0

[Master_MLA]
;AbortProcess = 0.000000E+0
AbortProcess = 0.000000E+0

[Master_Lena]
MiniReportFieldNumber = 0.000000E+0
StartTimeProcess = 4.812685E+2
EndTimeProcess = 5.077245E+2
ProcessDuration = 2.645595E+1

[_ReturnPos]
_X = 3.799999E+4
_Y = 2.000003E+4
_Z = -3.800015E+4

[PowerTest]
LO43.55 = 2.340645E-1
Tx43.55 = 4.388038E-2
Rx43.55 = 2.877497E-1
LO44.55 = 2.423477E-1
Tx44.55 = 4.734748E-2
Rx44.55 = 2.938686E-1
LO45.55 = 2.499441E-1
Tx45.55 = 5.117409E-2
Rx45.55 = 2.994566E-1
LO46.55 = 2.563161E-1
Tx46.55 = 5.468916E-2
Rx46.55 = 3.044190E-1
LO47.55 = 2.626142E-1
Tx47.55 = 5.831958E-2
Rx47.55 = 3.089857E-1
LO48.55 = 2.681588E-1
Tx48.55 = 6.139768E-2
Rx48.55 = 3.131818E-1
LO49.55 = 2.728739E-1
Tx49.55 = 6.481758E-2
Rx49.55 = 3.169234E-1
LO50.55 = 2.774546E-1
Tx50.55 = 6.853247E-2
Rx50.55 = 3.205513E-1
LO51.55 = 2.816026E-1
Tx51.55 = 7.163391E-2
Rx51.55 = 3.237672E-1
LO52.55 = 2.851817E-1
Tx52.55 = 7.504608E-2
Rx52.55 = 3.268812E-1
LO53.55 = 2.885769E-1
Tx53.55 = 7.820710E-2
Rx53.55 = 3.297002E-1
LO54.55 = 2.920255E-1
Tx54.55 = 8.148159E-2
Rx54.55 = 3.325181E-1
LO55.55 = 2.952245E-1
Tx55.55 = 8.489037E-2
Rx55.55 = 3.351773E-1
LO56.55 = 2.982475E-1
Tx56.55 = 8.863923E-2
Rx56.55 = 3.376926E-1
LO57.55 = 3.014941E-1
Tx57.55 = 9.256214E-2
Rx57.55 = 3.401090E-1
LO58.55 = 3.042433E-1
Tx58.55 = 9.635383E-2
Rx58.55 = 3.424498E-1
LO59.55 = 3.069806E-1
Tx59.55 = 1.000271E-1
Rx59.55 = 3.446110E-1
LO60.55 = 3.095705E-1
Tx60.55 = 1.033684E-1
Rx60.55 = 3.468541E-1
LO61.55 = 3.118255E-1
Tx61.55 = 1.068127E-1
Rx61.55 = 3.488431E-1
LO62.55 = 3.138969E-1
Tx62.55 = 1.097257E-1
Rx62.55 = 3.508374E-1
LO63.55 = 3.161439E-1
Tx63.55 = 1.125809E-1
Rx63.55 = 3.527688E-1
LO64.55 = 3.184854E-1
Tx64.55 = 1.155347E-1
Rx64.55 = 3.546986E-1
LO65.55 = 3.205298E-1
Tx65.55 = 1.184998E-1
Rx65.55 = 3.565564E-1
LO66.55 = 3.225264E-1
Tx66.55 = 1.219991E-1
Rx66.55 = 3.582146E-1
LO67.55 = 3.243225E-1
Tx67.55 = 1.252906E-1
Rx67.55 = 3.599405E-1
LO68.55 = 3.262088E-1
Tx68.55 = 1.284968E-1
Rx68.55 = 3.615775E-1
LO69.55 = 3.279704E-1
Tx69.55 = 1.316893E-1
Rx69.55 = 3.632774E-1
LO70.55 = 3.296204E-1
Tx70.55 = 1.350078E-1
Rx70.55 = 3.647459E-1
LO71.55 = 3.312487E-1
Tx71.55 = 1.380311E-1
Rx71.55 = 3.662711E-1
LO72.55 = 3.327904E-1
Tx72.55 = 1.414774E-1
Rx72.55 = 3.676973E-1
LO73.55 = 3.343417E-1
Tx73.55 = 1.444427E-1
Rx73.55 = 3.692326E-1
LO74.55 = 3.359332E-1
Tx74.55 = 1.478303E-1
Rx74.55 = 3.704962E-1
LO75.55 = 3.374998E-1
Tx75.55 = 1.512814E-1
Rx75.55 = 3.717837E-1

[Pick_FAC_Reference]
FAC_Left_X_Offset = 3.941520E+1

[ADMINISTRATION]
SubFolder_4_Path = "D:\TestMasterData\data"